materials = [
    'Acetic Acid',
    'Alkanet',
    'Alum',
    'Alumina',
    'Asbestos',
    'Arven oil',
    'Beeswax wax',
    'Beeswax soap',
    'Bentonite',
    'Benzalconium choride',
    'Casein',
    'Castor oil',
    'Coiza oil',
    'Chalk',
    'Cholorophyl',
    'Citric Acid',
    'Corn germ oil',
    'Coco nut oil',
    'Dyers broom',
    'Dyers chamomile',
    'Ethanol',
    'Gall oak apples',
    'Glycerin',
    'Hemp oil',
    'Iron chloride',
    'Iron sulfide',
    'Juniper berry oil',
    'Kermes',
    'Larch tree resin',
    'Lavender oil',
    'Lead',
    'Mica',
    'Mold',
    'Mercury',
    'Oak bark',
    'Reetha extract',
    'Shellac',
    'Soy lecithin'
]
